//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplicationPoc.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProductProvider")]
    public interface IProductProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductProvider/GetProduct", ReplyAction="http://tempuri.org/IProductProvider/GetProductResponse")]
        DataProvider.Product GetProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductProvider/GetProduct", ReplyAction="http://tempuri.org/IProductProvider/GetProductResponse")]
        System.Threading.Tasks.Task<DataProvider.Product> GetProductAsync(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductProviderChannel : WpfApplicationPoc.ServiceReference1.IProductProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductProviderClient : System.ServiceModel.ClientBase<WpfApplicationPoc.ServiceReference1.IProductProvider>, WpfApplicationPoc.ServiceReference1.IProductProvider {
        
        public ProductProviderClient() {
        }
        
        public ProductProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataProvider.Product GetProduct(int productId) {
            return base.Channel.GetProduct(productId);
        }
        
        public System.Threading.Tasks.Task<DataProvider.Product> GetProductAsync(int productId) {
            return base.Channel.GetProductAsync(productId);
        }
    }
}
